### ISSUE TITLE
NoClassDefFoundError while trying to run demo project

### ISSUE THREAD

**Issue by sgrekov** [lucasr/twoway-view#12]
I am getting an exception while trying to run demo project

 Caused by: java.lang.NoClassDefFoundError: android.support.v4.widget.EdgeEffectCompat
        at org.lucasr.twowayview.TwoWayView.setOverScrollMode(TwoWayView.java:936)
        at android.view.View.<init>(View.java:3237)
        at android.view.View.<init>(View.java:3295)
        at android.view.ViewGroup.<init>(ViewGroup.java:427)
        at android.widget.AdapterView.<init>(AdapterView.java:235)
        at org.lucasr.twowayview.TwoWayView.<init>(TwoWayView.java:287)
        at org.lucasr.twowayview.TwoWayView.<init>(TwoWayView.java:283)

**Comment by saikiran501** [comment]
Iam also getting the same exception which jar file should i import,I already imported library file but it's showing the same exception..
