### ISSUE TITLE
IllegalStateException: Tried to cache frame on undefined item

### ISSUE THREAD

**Issue by jacek-marchwicki** [lucasr/twoway-view#141]
```
java.lang.IllegalStateException: Tried to cache frame on undefined item
       at org.lucasr.twowayview.widget.StaggeredGridLayoutManager.cacheChildFrame(StaggeredGridLayoutManager.java:198)
       at org.lucasr.twowayview.widget.BaseLayoutManager.layoutChild(BaseLayoutManager.java:434)
       at org.lucasr.twowayview.TwoWayLayoutManager.setupChild(TwoWayLayoutManager.java:462)
       at org.lucasr.twowayview.TwoWayLayoutManager.makeAndAddView(TwoWayLayoutManager.java:473)
       at org.lucasr.twowayview.TwoWayLayoutManager.fillSpecific(TwoWayLayoutManager.java:279)
       at org.lucasr.twowayview.TwoWayLayoutManager.onLayoutChildren(TwoWayLayoutManager.java:705)
       at org.lucasr.twowayview.widget.BaseLayoutManager.onLayoutChildren(BaseLayoutManager.java:326)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1918)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2155)
       at android.view.View.layout(View.java:14860)
       at android.view.ViewGroup.layout(ViewGroup.java:4643)
       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:543)
       at android.view.View.layout(View.java:14860)
       at android.view.ViewGroup.layout(ViewGroup.java:4643)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:14860)
       at android.view.ViewGroup.layout(ViewGroup.java:4643)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:14860)
       at android.view.ViewGroup.layout(ViewGroup.java:4643)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1594)
       at android.view.View.layout(View.java:14860)
       at android.view.ViewGroup.layout(ViewGroup.java:4643)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
       at android.view.View.layout(View.java:14860)
       at android.view.ViewGroup.layout(ViewGroup.java:4643)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:14860)
       at android.view.ViewGroup.layout(ViewGroup.java:4643)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:14860)
       at android.view.ViewGroup.layout(ViewGroup.java:4643)
       at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:887)
       at android.view.View.layout(View.java:14860)
       at android.view.ViewGroup.layout(ViewGroup.java:4643)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:14860)
       at android.view.ViewGroup.layout(ViewGroup.java:4643)
       at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:502)
       at android.view.View.layout(View.java:14860)
       at android.view.ViewGroup.layout(ViewGroup.java:4643)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:14860)
       at android.view.ViewGroup.layout(ViewGroup.java:4643)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
       at android.view.View.layout(View.java:14860)
       at android.view.ViewGroup.layout(ViewGroup.java:4643)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:14860)
       at android.view.ViewGroup.layout(ViewGroup.java:4643)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2013)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1770)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1019)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5725)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5086)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Currently I could easily reproduce this issue but I will try prepare some example

**Comment by sharebooks** [comment]
Where I can get the latest code? In github master branch, It is still old code.
