### ISSUE TITLE
ArrayIndexOutOfBoundsException on fast scroll up

### ISSUE THREAD

**Issue by nikolavelimirovic** [lucasr/twoway-view#150]
Hi i have quite a lot of items in adapters dataset (> 500), and when i scroll to 300th item and then scroll really fast to the top i get this crash, tested on variety of devices (samsung s3, huawei p6, 7inch samsung tablet) and on all of them it is been reproduced easily with this use case. I am here for any questions you may have about this error :)

java.lang.ArrayIndexOutOfBoundsException: length=3; index=-1
            at org.lucasr.twowayview.widget.Lanes.getChildFrame(Lanes.java:211)
            at org.lucasr.twowayview.widget.BaseLayoutManager.layoutChild(BaseLayoutManager.java:437)
            at org.lucasr.twowayview.TwoWayLayoutManager.setupChild(TwoWayLayoutManager.java:462)
            at org.lucasr.twowayview.TwoWayLayoutManager.makeAndAddView(TwoWayLayoutManager.java:473)
            at org.lucasr.twowayview.TwoWayLayoutManager.fillBefore(TwoWayLayoutManager.java:253)
            at org.lucasr.twowayview.TwoWayLayoutManager.fillGap(TwoWayLayoutManager.java:240)
            at org.lucasr.twowayview.TwoWayLayoutManager.scrollBy(TwoWayLayoutManager.java:226)
            at org.lucasr.twowayview.TwoWayLayoutManager.scrollVerticallyBy(TwoWayLayoutManager.java:780)
            at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:2715)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)

**Comment by martijnvm** [comment]
The same error occurred to me when the grid is smoothScrolling and at the same time calling notifyDataSetChanged (or any variant). My quick and easy solution was doing my two actions in a sequence, so first scrolling and when the grid is idle it is notified.
