### ISSUE TITLE
ViewPager inside TwoWayView crash after scroll

### ISSUE THREAD

**Issue by jamesjtswl** [lucasr/twoway-view#234]
Hello, I have an issue on staggered grid (Vertical) which I put view pager inside. When i try to scroll the view pager, the application crash. An error report on onRequestDisallowInterceptTouchEvent function in twowayview class. Could you please help me ? 

Thanks in advance. 

@eneim Here is my crash log 

```
java.lang.AbstractMethodError: abstract method not implemented
        at org.lucasr.twowayview.ClickItemTouchListener.onRequestDisallowInterceptTouchEvent(ClickItemTouchListener.java)
        at android.support.v7.widget.RecyclerView.requestDisallowInterceptTouchEvent(RecyclerView.java:2109)
        at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:2504)
        at android.support.v4.view.ViewPager.requestParentDisallowInterceptTouchEvent(ViewPager.java:2138)
        at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2060)
        at android.view.View.dispatchTouchEvent(View.java:8135)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2416)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2140)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2155)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2155)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2155)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2155)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2155)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2155)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2422)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2155)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2295)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1622)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2565)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2243)
        at android.view.View.dispatchPointerEvent(View.java:8343)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4773)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4639)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4197)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4251)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4220)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4331)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4228)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4388)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4197)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4251)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4220)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4228)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4197)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6564)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6481)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6452)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6417)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6644)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6617)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6663)
        at andr
```

**Comment by eneim** [comment]
Could you please upload/paste your crash log report here?

**Comment by pranandpatil** [comment]
lkjnl
