### ISSUE TITLE
android.widget.RelativeLayout$LayoutParams cannot be cast to org.lucasr.twowayview.TwoWayView$LayoutParams

### ISSUE THREAD

**Issue by bruthnan** [lucasr/twoway-view#274]
fatal error : android.widget.RelativeLayout$LayoutParams cannot be cast to org.lucasr.twowayview.TwoWayView$LayoutParams
                                                           java.lang.ClassCastException: android.widget.RelativeLayout$LayoutParams cannot be cast to org.lucasr.twowayview.TwoWayView$LayoutParams
                                                               at org.lucasr.twowayview.TwoWayView.setupChild(TwoWayView.java:5054)
                                                               at org.lucasr.twowayview.TwoWayView.makeAndAddView(TwoWayView.java:5035)
                                                               at org.lucasr.twowayview.TwoWayView.fillSpecific(TwoWayView.java:5171)

**Comment by tuanth89** [comment]
@bruthnan i have same this issue, how resolve this ??? Thanks

**Comment by aresthelord** [comment]
Recyclerview.layoutparams maybe
