### ISSUE TITLE
Crash in sample App : android.os.BadParcelableException: ClassNotFoundException when unmarshalling

### ISSUE THREAD

**Issue by catalinv** [lucasr/twoway-view#88]
Steps to reproduce:
1) From Developer Options - mark Don't keep activities
2) Leave the sample app in background, when the app is opened again it crashes
Crash Log:
 Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 
at android.os.Parcel.readParcelableCreator(Parcel.java:2105)
at android.os.Parcel.readParcelable(Parcel.java:2055)
at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
at android.view.View$BaseSavedState.<init>(View.java:17960)
at org.lucasr.twowayview.TwoWayLayoutManager$SavedState.<init>(TwoWayLayoutManager.java:931)
at org.lucasr.twowayview.widget.BaseLayoutManager$LanedSavedState.<init>(BaseLayoutManager.java:522)
at org.lucasr.twowayview.widget.BaseLayoutManager$LanedSavedState.<init>(BaseLayoutManager.java:521)
at org.lucasr.twowayview.widget.BaseLayoutManager$LanedSavedState$1.createFromParcel(BaseLayoutManager.java:573)
at org.lucasr.twowayview.widget.BaseLayoutManager$LanedSavedState$1.createFromParcel(BaseLayoutManager.java:1)

**Comment by kenyee** [comment]
Thanks for the clue (google finds this page when looking for that error msg)...had the same issue when extending from BaseSavedState. 
Remember to save your superstate though...I didn't see how you did this in your SavedState class but it should be saved and restored.
